image: registry.gitlab.com/robit.a/spatsoc

stages:
 - test
 - coverage

test_job:
  stage: test
  script:
  - R CMD build . --no-build-vignettes --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
  only:
  - master

coverage_job:
  stage: coverage
  when: on_success
  only:
    - master
  script:
    - install2.r covr
    - r -e 'devtools::install()'
    - r -e 'covr::codecov(type = c("tests", "examples"), quiet = FALSE)'
