stages:
 - test
 - coverage

test_latest:
  image: registry.gitlab.com/robit.a/spatsoc:latest
  stage: test
  script:
  - R CMD build . --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-manual
  only:
  - master


test_devel:
  image: registry.gitlab.com/robit.a/spatsoc:devel
  stage: test
  script:
  - R CMD build . --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-manual
  only:
  - master

coverage_job:
  image: registry.gitlab.com/robit.a/spatsoc:latest
  stage: coverage
  when: on_success
  only:
    - master
  script:
    - install2.r covr
    - r -e 'devtools::install()'
    - r -e 'covr::codecov(type = c("tests", "examples"), quiet = FALSE, token = "028df4b6-36a6-4a68-8a70-e69d4dd79fc1")'
